const grid=document.getElementById("products"),offers=document.getElementById("offers"),noOffers=document.getElementById("noOffers"),search=document.getElementById("search"),categories=document.getElementById("categories"),empty=document.getElementById("empty"),clearSearch=document.getElementById("clearSearch"),backTop=document.getElementById("backTop");
document.getElementById("year").textContent=new Date().getFullYear();let activeCategory="Todos",products=[],fallbackProducts=window.products||[];
function normalizeProduct(p){return{ id:p.id,title:p.title??p.name??"Producto",description:p.description??p.descripcion??"",price:p.price??p.precio??"",currency:p.currency??p.moneda??"PEN",category:p.category??p.categoria??"General",image:p.image_url??p.image??p.imagen??"",link:p.link??p.url??p.enlace??"#",badge:p.badge??p.etiqueta??"",active:p.active!==false};}
async function loadProducts(){try{const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const{data,error}=await client.from("products").select("*");if(error)throw error;products=(data||[]).map(normalizeProduct).filter(p=>p.active);if(!products.length&&data&&data.length){products=data.map(normalizeProduct)}if(!products.length&&fallbackProducts.length)products=fallbackProducts.map(normalizeProduct);console.info("IKMA Market: productos recuperados de Supabase:",products.length)}catch(e){console.error("No se pudo cargar el catálogo de Supabase:",e);products=fallbackProducts.map(normalizeProduct)}buildCategories();renderOffers();render()}
function buildCategories(){const list=["Todos",...new Set(products.map(p=>p.category).filter(Boolean))];categories.innerHTML=list.map(c=>'<button class="filter '+(c==="Todos"?"active":"")+'" data-category="'+escapeAttr(c)+'">'+escapeHtml(c)+"</button>").join("")}
categories.addEventListener("click",e=>{const b=e.target.closest(".filter");if(!b)return;activeCategory=b.dataset.category;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
search.addEventListener("input",()=>{clearSearch.hidden=!search.value;render()});clearSearch.addEventListener("click",()=>{search.value="";clearSearch.hidden=true;search.focus();render()});window.addEventListener("scroll",()=>backTop.classList.toggle("visible",window.scrollY>500),{passive:true});backTop.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
function isOffer(p){const v=((p.badge||"")+" "+(p.category||"")).toLowerCase();return v.includes("oferta")||v.includes("promo")||v.includes("descuento")||v.includes("%")}
function getDiscount(p){const m=String(p.badge||"").match(/(\d{1,2})\s*%/);return m?Math.min(99,Math.max(1,Number(m[1]))):null}
function card(p){const d=getDiscount(p),old=d&&p.price?Number(p.price)/(1-d/100):null;return '<article class="product '+(isOffer(p)?"offer-card":"")+'"><div class="product-img">'+(p.image?'<img src="'+escapeAttr(p.image)+'" alt="'+escapeAttr(p.title)+'" loading="lazy">':'<span>IKMA</span>')+'</div><div class="product-body"><span class="badge">'+escapeHtml(p.badge||p.category||"PRODUCTO")+'</span><h3>'+escapeHtml(p.title)+'</h3><p>'+escapeHtml(p.description||"")+'</p><div class="product-bottom"><div class="price-line"><span class="price">'+escapeHtml(formatPrice(p.price,p.currency))+'</span>'+(old?'<span class="old-price">'+escapeHtml(formatPrice(old,p.currency))+"</span>":"")+(d?'<span class="discount">'+d+"% OFF</span>":"")+'</div><a class="buy" href="'+escapeAttr(p.link||"#")+'" target="_blank" rel="noopener noreferrer">🛒 Ver producto</a></div></div></article>"}
function renderOffers(){const op=products.filter(isOffer).slice(0,3);noOffers.classList.toggle("hidden",op.length>0);offers.classList.toggle("hidden",op.length===0);offers.innerHTML=op.map(card).join("")}
function render(){const term=search.value.trim().toLowerCase();const filtered=products.filter(p=>{const mc=activeCategory==="Todos"||p.category===activeCategory;const txt=[p.title,p.description,p.category,p.badge].join(" ").toLowerCase();return mc&&txt.includes(term)});empty.classList.toggle("hidden",filtered.length>0);grid.innerHTML=filtered.map(card).join("")}
function formatPrice(price,currency){if(price===null||price===undefined||price==="")return"Consultar";const c=String(currency||"PEN").toUpperCase();return(c==="USD"||c==="US$"||c==="$"?"US$":"S/")+" "+Number(price).toFixed(2)}
function escapeHtml(value){return String(value??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}function escapeAttr(value){return escapeHtml(value)}loadProducts();