const grid=document.getElementById("products"),offers=document.getElementById("offers"),noOffers=document.getElementById("noOffers"),search=document.getElementById("search"),categories=document.getElementById("categories"),empty=document.getElementById("empty"),clearSearch=document.getElementById("clearSearch"),backTop=document.getElementById("backTop"),catalogStatus=document.getElementById("catalogStatus");
document.getElementById("year").textContent=new Date().getFullYear();let activeCategory="Todos",products=[];
function normalizeProduct(p){return{id:p.id,title:p.title??"Producto",description:p.description??"",price:p.price??"",currency:p.currency??"PEN",category:p.category??"General",image:p.image_url??"",link:p.link??"#",badge:p.badge??"",active:p.active===true||p.active==="true"||p.active===1};}
async function loadProducts(){setCatalogStatus("Cargando productos…","loading");try{const url=SUPABASE_URL.replace(/\/$/,"")+"/rest/v1/products?select=*";const res=await fetch(url,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:"Bearer "+SUPABASE_PUBLISHABLE_KEY,Accept:"application/json"}});const body=await res.text();if(!res.ok)throw new Error("Supabase HTTP "+res.status+": "+body);const rows=JSON.parse(body);if(!Array.isArray(rows))throw new Error("La respuesta de Supabase no es una lista.");products=rows.map(normalizeProduct).filter(p=>p.active);if(products.length){setCatalogStatus("✓ "+products.length+" productos cargados correctamente.","success")}else if(rows.length){products=rows.map(normalizeProduct);setCatalogStatus("Hay "+rows.length+" productos, pero no están activos.","warning")}else{setCatalogStatus("La tabla products no tiene productos.","warning")}console.info("IKMA Market: productos recuperados:",products.length)}catch(e){console.error(e);products=[];setCatalogStatus("Error cargando productos: "+(e.message||String(e)),"error")}buildCategories();renderOffers();render()}
function setCatalogStatus(message,type){if(!catalogStatus)return;catalogStatus.hidden=false;catalogStatus.className="catalog-status "+(type||"");catalogStatus.textContent=message}
function buildCategories(){const list=["Todos",...new Set(products.map(p=>p.category).filter(Boolean))];categories.innerHTML=list.map(c=>'<button class="filter '+(c==="Todos"?"active":"")+'" data-category="'+escapeAttr(c)+'">'+escapeHtml(c)+"</button>").join("")}
categories.addEventListener("click",e=>{const b=e.target.closest(".filter");if(!b)return;activeCategory=b.dataset.category;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
search.addEventListener("input",()=>{clearSearch.hidden=!search.value;render()});clearSearch.addEventListener("click",()=>{search.value="";clearSearch.hidden=true;search.focus();render()});window.addEventListener("scroll",()=>backTop.classList.toggle("visible",window.scrollY>500),{passive:true});backTop.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
function isOffer(p){const v=((p.badge||"")+" "+(p.category||"")).toLowerCase();return v.includes("oferta")||v.includes("promo")||v.includes("descuento")||v.includes("%")}
function getDiscount(p){const m=String(p.badge||"").match(/(\d{1,2})\s*%/);return m?Math.min(99,Math.max(1,Number(m[1]))):null}
function card(p){const d=getDiscount(p),old=d&&p.price?Number(p.price)/(1-d/100):null;return '<article class="product '+(isOffer(p)?"offer-card":"")+'"><div class="product-img">'+(p.image?'<img src="'+escapeAttr(p.image)+'" alt="'+escapeAttr(p.title)+'" loading="lazy">':'<span>IKMA</span>')+'</div><div class="product-body"><span class="badge">'+escapeHtml(p.badge||p.category||"PRODUCTO")+'</span><h3>'+escapeHtml(p.title)+'</h3><p>'+escapeHtml(p.description||"")+'</p><div class="product-bottom"><div class="price-line"><span class="price">'+escapeHtml(formatPrice(p.price,p.currency))+'</span>'+(old?'<span class="old-price">'+escapeHtml(formatPrice(old,p.currency))+"</span>":"")+(d?'<span class="discount">'+d+"% OFF</span>":"")+'</div><a class="buy" href="'+escapeAttr(p.link||"#")+'" target="_blank" rel="noopener noreferrer">🛒 Ver producto</a></div></div></article>"}
function renderOffers(){const op=products.filter(isOffer).slice(0,3);noOffers.classList.toggle("hidden",op.length>0);offers.classList.toggle("hidden",op.length===0);offers.innerHTML=op.map(card).join("")}
function render(){const term=search.value.trim().toLowerCase();const filtered=products.filter(p=>{const mc=activeCategory==="Todos"||p.category===activeCategory;const txt=[p.title,p.description,p.category,p.badge].join(" ").toLowerCase();return mc&&txt.includes(term)});empty.classList.toggle("hidden",filtered.length>0);grid.innerHTML=filtered.map(card).join("")}
function formatPrice(price,currency){if(price===null||price===undefined||price==="")return"Consultar";const c=String(currency||"PEN").toUpperCase();return(c==="USD"||c==="US$"||c==="$"?"US$":"S/")+" "+Number(price).toFixed(2)}
function escapeHtml(value){return String(value??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}function escapeAttr(value){return escapeHtml(value)}loadProducts();